### ISSUE TITLE
Candidated from 15 000 to 20 000

### ISSUE THREAD

**Issue by gnufinder** [gnufinder/special-prime#12]
? length(v)
%17 = 700
? for(j=1,length(v),print(v[j]))
15000
15004
15006
15018
15030
15044
15047
15063
15066
15079
15080
15084
15086
15087
15107
15110
15112
15142
15151
15158
15162
15164
15170
15172
15175
15183
15190
15191
15192
15198
15203
15218
15228
15239
15243
15252
15266
15271
15282
15291
15295
15299
15310
15315
15316
15326
15352
15360
15363
15367
15372
15375
15383
15396
15398
15399
15423
15427
15428
15432
15435
15438
15443
15444
15448
15455
15459
15476
15484
15496
15502
15504
15506
15519
15535
15552
15560
15564
15571
15579
15582
15608
15619
15631
15634
15635
15639
15643
15648
15666
15668
15672
15675
15683
15696
15699
15719
15726
15727
15728
15739
15755
15758
15767
15774
15780
15788
15798
15799
15803
15806
15811
15818
15835
15840
15858
15860
15862
15863
15866
15868
15888
15894
15895
15899
15908
15912
15916
15919
15923
15928
15942
15954
15958
15960
15980
15982
15999
16002
16018
16048
16054
16056
16058
16063
16072
16075
16088
16095
16107
16108
16111
16116
16118
16122
16127
16136
16148
16150
16152
16160
16162
16167
16168
16171
16174
16175
16176
16178
16179
16188
16191
16192
16199
16200
16203
16210
16228
16240
16252
16258
16262
16287
16291
16294
16299
16300
16303
16307
16308
16312
16314
16318
16340
16355
16356
16359
16362
16363
16372
16382
16387
16395
16416
16422
16435
16436
16467
16468
16480
16488
16496
16498
16506
16507
16511
16527
16536
16539
16546
16551
16566
16567
16570
16571
16595
16602
16612
16616
16646
16648
16651
16652
16663
16667
16672
16678
16679
16686
16691
16695
16700
16706
16708
16711
16720
16731
16742
16750
16763
16772
16775
16776
16788
16796
16799
16811
16812
16818
16828
16830
16840
16850
16856
16863
16866
16870
16875
16888
16891
16892
16906
16908
16912
16916
16935
16939
16943
16947
16948
16950
16952
16955
16975
16976
16982
17023
17028
17035
17044
17059
17070
17079
17080
17083
17091
17119
17120
17123
17127
17132
17139
17140
17142
17159
17160
17162
17171
17184
17190
17195
17196
17202
17222
17227
17235
17248
17251
17256
17259
17263
17271
17275
17280
17283
17298
17300
17308
17312
17330
17339
17343
17350
17363
17375
17386
17396
17404
17407
17411
17418
17422
17432
17439
17440
17451
17471
17480
17483
17488
17499
17500
17506
17510
17520
17527
17538
17543
17547
17548
17550
17558
17559
17563
17574
17579
17591
17595
17612
17619
17635
17648
17659
17660
17671
17683
17707
17711
17712
17718
17739
17740
17750
17751
17767
17770
17771
17775
17780
17791
17795
17815
17830
17832
17838
17850
17860
17863
17880
17890
17918
17919
17930
17935
17955
17956
17958
17970
17971
17974
17980
18007
18012
18034
18035
18043
18055
18056
18059
18060
18067
18079
18082
18087
18090
18098
18103
18119
18123
18140
18146
18147
18167
18168
18174
18186
18188
18191
18198
18200
18202
18216
18223
18227
18235
18239
18243
18252
18262
18267
18279
18286
18290
18291
18299
18303
18319
18322
18331
18348
18350
18354
18356
18368
18370
18379
18380
18392
18395
18396
18418
18438
18447
18466
18478
18483
18502
18510
18519
18523
18528
18540
18546
18550
18551
18559
18570
18583
18584
18587
18588
18591
18600
18607
18610
18611
18615
18618
18622
18644
18646
18650
18656
18658
18671
18679
18686
18690
18700
18708
18719
18726
18728
18731
18735
18742
18755
18758
18759
18763
18771
18778
18779
18780
18796
18798
18816
18836
18838
18839
18840
18843
18846
18852
18856
18859
18872
18878
18879
18880
18884
18888
18900
18912
18947
18956
18959
18967
18968
18970
18975
18978
18979
18982
19003
19016
19020
19024
19027
19039
19042
19058
19060
19063
19064
19072
19091
19096
19104
19106
19112
19138
19147
19148
19156
19158
19162
19171
19179
19180
19184
19204
19207
19224
19231
19238
19243
19246
19252
19256
19260
19264
19267
19270
19275
19279
19286
19290
19292
19304
19308
19326
19330
19335
19347
19348
19350
19366
19376
19383
19384
19390
19391
19395
19402
19407
19412
19424
19426
19447
19455
19456
19462
19464
19471
19472
19475
19482
19491
19503
19508
19511
19512
19527
19528
19531
19532
19547
19558
19562
19563
19586
19588
19591
19596
19599
19618
19634
19635
19636
19639
19648
19654
19655
19671
19672
19674
19675
19678
19680
19682
19686
19687
19694
19710
19714
19719
19728
19732
19734
19735
19738
19751
19768
19770
19786
19787
19795
19798
19802
19806
19816
19826
19827
19835
19847
19854
19866
19894
19911
19912
19914
19915
19923
19926
19951
19971
19982
19986
19994
?

**Comment by paologalliani** [comment]
Prime for n=19179!
