### ISSUE TITLE
Candidates from 100 000 to 200 000 with residue 1

### ISSUE THREAD

**Issue by gnufinder** [gnufinder/special-prime#27]
? print(length(v))
465
? for(j=1,length(v),print(v[j]))
100195
100216
100255
100276
100396
100456
100675
101032
101071
101452
101551
101632
101848
101908
101911
102448
102547
102808
102847
104023
104200
104440
104479
104599
104800
104860
104959
105019
105259
105319
105556
105616
105796
106555
106612
106972
107152
107212
107251
107272
107311
107551
107848
108007
108088
108127
108148
108247
108388
108487
108547
108727
109723
110080
110299
110719
110839
111079
111199
111736
111796
111835
111916
112015
112552
113251
113608
113968
114427
114547
115003
116260
116599
116740
116779
117076
117256
117556
117616
117916
118015
118195
118252
118312
118852
119032
119092
119131
119647
119827
120883
121063
122059
122260
122299
122320
122359
122659
122836
123175
123196
123256
123475
123535
123556
123616
123895
124252
124351
124432
124612
124651
124771
124852
124912
124951
125011
125188
125248
125527
125587
125668
125887
126007
126028
126067
127243
127363
127423
127480
127660
127879
127939
127960
128380
128836
128896
129055
129076
129256
129376
129475
129595
129775
130012
130171
130231
130951
131308
131368
133360
133363
133480
133540
133660
133759
134119
134140
134200
134716
134935
135055
135436
136012
136192
136351
136411
136432
136471
136591
137128
137287
137488
138703
138823
139240
139420
139459
139480
139519
139639
139840
139879
139900
140356
140416
140755
141256
141295
141535
141592
141751
141892
142192
142291
142312
142591
142651
142828
143107
143368
143407
144823
145000
145339
145360
145480
145519
145600
145720
145999
146596
146635
146776
147055
147295
147532
147592
147652
147892
147952
148072
148708
148807
149107
149587
149647
150283
150403
150583
150763
150820
150940
151240
151519
151540
151600
151759
152056
152176
152395
152476
152536
152815
152935
153112
153175
153412
153511
153652
153832
154231
154291
154348
154528
154687
154747
156163
156283
156463
156760
157000
157120
157159
157240
157339
157420
157540
157579
157936
158116
158236
158275
158296
158356
158416
158536
159172
159412
159652
159712
159931
160408
160447
160468
160567
160708
160747
161167
161923
162463
162523
162799
162919
163039
163159
163240
163360
163399
163519
164236
164356
164476
164575
164932
164992
165052
165112
165151
165232
165292
165472
165511
165712
165871
165928
166048
166288
166567
166588
166708
167047
167443
167503
167623
167923
168400
168580
168859
168940
169120
169339
169576
169996
170095
170116
170296
170455
170515
170632
171172
171811
171868
172468
172708
173263
173383
174100
174103
174160
174220
174280
174379
174940
174979
175159
175936
176035
176095
176275
176395
176632
176692
176731
176752
176791
177031
177232
177271
177868
178267
178348
178387
178408
178687
178807
179980
179983
180160
180379
180640
180799
180919
181636
181675
182155
182392
182551
182872
182992
183172
183451
183688
183748
183847
183928
183988
184048
184228
184348
184567
185023
185083
185443
185743
185860
186040
186160
186220
186439
186499
186700
187495
187516
187615
188155
188332
188431
188632
188671
188971
189271
189568
189787
189808
189847
189868
190108
191443
191623
191959
192040
192259
192400
192856
193276
193516
193912
194311
194332
194431
194731
195427
195847
195988
196843
197680
197740
197800
198220
198280
198319
198439
198556
198559
198616
198736
198796
198976
199036
199156
199336
199495
199516
199795
?

**Comment by paologalliani** [comment]
No prime found res 1 mod 7 in this range
